// <auto-generated />
using System;
using HarrisCountyAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarrisCountyAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812184040_AddDocumentRegions")]
    partial class AddDocumentRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime?>("IngestionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngestionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionStatus");

                    b.ToTable("KnowledgeDocuments", (string)null);
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.NormalizedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DocumentId");

                    b.ToTable("NormalizedDocuments", (string)null);
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.ValidationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ValidationReports", (string)null);
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.Document", b =>
                {
                    b.HasOne("HarrisCountyAI.Domain.Entities.Case", null)
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.NormalizedDocument", b =>
                {
                    b.OwnsMany("HarrisCountyAI.Domain.Entities.DocumentField", "Fields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double?>("Confidence")
                                .HasColumnType("float");

                            b1.Property<bool?>("IsChecked")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSigned")
                                .HasColumnType("bit");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<Guid>("NormalizedDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("PageNumber")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("NormalizedDocumentId");

                            b1.ToTable("NormalizedDocumentFields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NormalizedDocumentId");

                            b1.OwnsOne("HarrisCountyAI.Domain.ValueObjects.BoundingBox", "KeyBoundingBox", b2 =>
                                {
                                    b2.Property<Guid>("DocumentFieldId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Height")
                                        .HasColumnType("float")
                                        .HasColumnName("KeyBoundingBox_Height");

                                    b2.Property<int>("PageNumber")
                                        .HasColumnType("int")
                                        .HasColumnName("KeyBoundingBox_PageNumber");

                                    b2.Property<double>("Width")
                                        .HasColumnType("float")
                                        .HasColumnName("KeyBoundingBox_Width");

                                    b2.Property<double>("X")
                                        .HasColumnType("float")
                                        .HasColumnName("KeyBoundingBox_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("float")
                                        .HasColumnName("KeyBoundingBox_Y");

                                    b2.HasKey("DocumentFieldId");

                                    b2.ToTable("NormalizedDocumentFields");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentFieldId");
                                });

                            b1.OwnsOne("HarrisCountyAI.Domain.ValueObjects.BoundingBox", "ValueBoundingBox", b2 =>
                                {
                                    b2.Property<Guid>("DocumentFieldId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Height")
                                        .HasColumnType("float")
                                        .HasColumnName("ValueBoundingBox_Height");

                                    b2.Property<int>("PageNumber")
                                        .HasColumnType("int")
                                        .HasColumnName("ValueBoundingBox_PageNumber");

                                    b2.Property<double>("Width")
                                        .HasColumnType("float")
                                        .HasColumnName("ValueBoundingBox_Width");

                                    b2.Property<double>("X")
                                        .HasColumnType("float")
                                        .HasColumnName("ValueBoundingBox_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("float")
                                        .HasColumnName("ValueBoundingBox_Y");

                                    b2.HasKey("DocumentFieldId");

                                    b2.ToTable("NormalizedDocumentFields");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentFieldId");
                                });

                            b1.Navigation("KeyBoundingBox");

                            b1.Navigation("ValueBoundingBox");
                        });

                    b.OwnsMany("HarrisCountyAI.Domain.Entities.DocumentPage", "Pages", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("NormalizedDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PageNumber")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("NormalizedDocumentId");

                            b1.ToTable("NormalizedDocumentPages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NormalizedDocumentId");
                        });

                    b.Navigation("Fields");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.ValidationReport", b =>
                {
                    b.OwnsMany("HarrisCountyAI.Domain.Entities.ValidationReportItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DocumentType")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("ExtractedValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<int?>("PageNumber")
                                .HasColumnType("int");

                            b1.Property<string>("Requirement")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<Guid>("ValidationReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ValidationType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("ValidationReportId");

                            b1.ToTable("ValidationReportItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ValidationReportId");

                            b1.OwnsOne("HarrisCountyAI.Domain.ValueObjects.BoundingBox", "BoundingBox", b2 =>
                                {
                                    b2.Property<Guid>("ValidationReportItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Height")
                                        .HasColumnType("float")
                                        .HasColumnName("BoundingBox_Height");

                                    b2.Property<int>("PageNumber")
                                        .HasColumnType("int")
                                        .HasColumnName("BoundingBox_PageNumber");

                                    b2.Property<double>("Width")
                                        .HasColumnType("float")
                                        .HasColumnName("BoundingBox_Width");

                                    b2.Property<double>("X")
                                        .HasColumnType("float")
                                        .HasColumnName("BoundingBox_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("float")
                                        .HasColumnName("BoundingBox_Y");

                                    b2.HasKey("ValidationReportItemId");

                                    b2.ToTable("ValidationReportItems");

                                    b2.WithOwner()
                                        .HasForeignKey("ValidationReportItemId");
                                });

                            b1.Navigation("BoundingBox");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("HarrisCountyAI.Domain.Entities.Case", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
